/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.Bag;

/**
 *
 * @author andyg
 */
public class InputPanel extends javax.swing.JPanel {

    private JPanel container;
    /**
     * Creates new form NewJPanel
     */
    public InputPanel(JPanel container) {
        initComponents();
        this.container=container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        sumBagsText = new javax.swing.JTextField();
        maxWeightText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        valuesText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weightText = new javax.swing.JTextArea();
        continueBut1 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setText("Total bags");

        sumBagsText.setText("20");
        sumBagsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumBagsTextActionPerformed(evt);
            }
        });

        maxWeightText.setText("40");
        maxWeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxWeightTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel5.setText("Max weight");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setText("Bag values(responsive to the amout of total bags,exg input: 5,6,8,4)");

        valuesText.setColumns(20);
        valuesText.setRows(5);
        valuesText.setText("1,2,3,4,5,6,7,8,9,10,5,4,6,3,8,4,4,15,10,7");
        jScrollPane2.setViewportView(valuesText);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setText("Bag weight(responsive to the amout of total bags,exg input: 3,5,10,8)");

        weightText.setColumns(20);
        weightText.setRows(5);
        weightText.setText("3,4,6,7,6,10,4,8,5,4,1,5,8,16,2,3,5,6,3,1");
        jScrollPane1.setViewportView(weightText);

        continueBut1.setText("Continue");
        continueBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(continueBut1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxWeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sumBagsText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumBagsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maxWeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueBut1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sumBagsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumBagsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumBagsTextActionPerformed

    private void maxWeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxWeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxWeightTextActionPerformed

    private void continueBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBut1ActionPerformed
        int sumBags=0;
        int maxWeight=0;
        String bagValues="";
        String bagWeight="";
        try{
            sumBags=Integer.parseInt(sumBagsText.getText());
            maxWeight=Integer.parseInt(maxWeightText.getText());
            bagValues=valuesText.getText();
            bagWeight=weightText.getText();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please input valid total bags or max weight.");
            return;
        }
        try{
            String[] valuesS=bagValues.split(",");
            int[] values=new int[valuesS.length];
            for(int i=0;i<values.length;i++) values[i]=Integer.parseInt(valuesS[i]);
            String[] weightS=bagWeight.split(",");
            int[] weights=new int[weightS.length];
            for(int i=0;i<weights.length;i++) weights[i]=Integer.parseInt(weightS[i]);
            if(weights.length!=sumBags||values.length!=sumBags){
                JOptionPane.showMessageDialog(null, "The number of bag weights or values are not apprepriate with the amout of total bags.");
                return;
            }
            Bag[] bags=new Bag[sumBags];
            for(int i=0;i<sumBags;i++){
                bags[i]=new Bag();
                bags[i].setValue(values[i]);
                bags[i].setWeight(weights[i]);
            }
            ResultPanel panel=new ResultPanel(sumBags,maxWeight,bags,container);
            CardLayout layout=(CardLayout)container.getLayout();
            container.add("BagInfoPanel",panel);
            layout.next(container);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please input valid values or weights.");
        }
    }//GEN-LAST:event_continueBut1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueBut1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField maxWeightText;
    private javax.swing.JTextField sumBagsText;
    private javax.swing.JTextArea valuesText;
    private javax.swing.JTextArea weightText;
    // End of variables declaration//GEN-END:variables
}
