/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.Bag;
import main.GA_bags;

/**
 *
 * @author andyg
 */
public class ResultPanel extends javax.swing.JPanel {

    private int sumbags;
    private int maxWeight;
    private Bag[] bags;
    private JPanel container;
    /**
     * Creates new form BagInfoPanel
     */
    public ResultPanel(int sumbags,int maxWeight,Bag[] bags,JPanel container) {
        initComponents();
        this.sumbags=sumbags;
        this.maxWeight=maxWeight;
        this.bags=bags;
        this.container=container;
        displayTable(sumbags,maxWeight,bags);
    }
    
    private void displayTable(int sumbags,int maxWeight,Bag[] bags){
        GA_bags ga=new GA_bags(10000,sumbags, maxWeight, bags);
        int generationCount=1;
        DefaultTableModel dtm=(DefaultTableModel)table.getModel();
        dtm.setRowCount(0);
        for(int x=0;x<100;x++){
            Object[] row=new Object[5];
            int index=ga.getPopulation().calculateFittest();
            String bestGenes="";
            for(int gene:ga.getPopulation().getIndividuals().get(index).getGenes()){
                bestGenes+=gene;
            }
            int fittest=ga.getPopulation().getIndividuals().get(index).calculteFitness();
            double ave=ga.getPopulation().calculateAverage();
            int fittestWeight=ga.getPopulation().getIndividuals().get(index).calculateWeight();
            row[0]=generationCount;
            row[1]=bestGenes;
            row[2]=fittestWeight;
            row[3]=fittest;
            row[4]=ave;
            dtm.addRow(row);
            ga.logging(generationCount);
            ga.selection();
            ga.crossover();
            ga.mutatation();
            ga.addChildern();
            generationCount++;
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        backBut = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Generation", "The gene of fittest individual", "Fittest Weight", "Best fitness", "Average fitness"
            }
        ));
        jScrollPane1.setViewportView(table);

        backBut.setText("< Back");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBut))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addGap(83, 83, 83)
                .addComponent(backBut)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        CardLayout layout=(CardLayout)container.getLayout();
        container.remove(this);
        layout.previous(container);
        // TODO add your handling code here:
    }//GEN-LAST:event_backButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
